prefixes = {}
prefixes["24-24"] = {
    "yocto": "y",
    "zepto":"z",
    "atto":"a",
    "femto":"f",
    "pico":"p",
    "nano":"n",
    "micro":"µ",
    "milli":"m",
    "centi":"c",
    "deci":"d",
    "deca":"da",
    "hecto":"h",
    "kilo":"k",
    "mega":"M",
    "giga":"G",
    "tera":"T",
    "peta":"P",
    "exa":"E",
    "zetta":"Z",
    "yotta":"Y",
}
prefixes["3-3"] = {
    "milli":"m",
    "centi":"c",
    "deci":"d",
    "deca":"da",
    "hecto":"h",
    "kilo":"k",
}
prefixes["15-15"] = {
    "femto":"f",
    "pico":"p",
    "nano":"n",
    "micro":"µ",
    "milli":"m",
    "centi":"c",
    "deci":"d",
    "deca":"da",
    "hecto":"h",
    "kilo":"k",
    "mega":"M",
    "giga":"G",
    "tera":"T",
    "peta":"P",
}
